server:
  port: 8082
spring:
  application:
    name: microservice-fraud
  jackson:
    serialization.write_dates_as_timestamps: false

  datasource:
    username: 'postgres'
    password: 'postgres'
    url: jdbc:postgresql://localhost:5432/fraud
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true